export const ADD_INPUT_VALUE='ADD_INPUT_VALUE';
export const SUB_INPUT_VALUE='SUB_INPUT_VALUE';
export const MUL_INPUT_VALUE='MUL_INPUT_VALUE';
export const DIV_INPUT_VALUE='DIV_INPUT_VALUE';


export const ADD_INPUT_TEXT='ADD_INPUT_TEXT'